/**
 * Premium Executive PDF Report Generator
 * Generates an outstanding corporate-grade PDF security report with geometric accents,
 * left accent branding bars, KPI dashboards, custom-colored status metrics,
 * horizontal severity share percentage indicator progress bars, and high-readability detailed finding grids.
 */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const SEVERITY_COLORS = {
  Critical: [239, 68, 68], // Modern Soft Crimson
  High: [249, 115, 22],     // Energetic Amber Orange
  Medium: [234, 179, 8],    // Warm Gold Yellow
  Low: [6, 182, 212],       // Soft Clean Teal
};

function addPageHeader(doc, pageWidth) {
  // Slim Royal Indigo branding top bar
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 4, "F");

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text("AI Code Reviewer & Security Auditor", 14, 12);
  
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.text("Confidential Security Audit Report", pageWidth - 14, 12, { align: "right" });

  // Elegant dividing line
  doc.setDrawColor(241, 245, 249);
  doc.setLineWidth(0.5);
  doc.line(14, 15, pageWidth - 14, 15);
}

function addPageFooter(doc, pageWidth, pageHeight, pageNum) {
  // Thin footer separator line
  doc.setDrawColor(241, 245, 249);
  doc.setLineWidth(0.5);
  doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.text("Generated by AI Code Reviewer & Security Auditor", 14, pageHeight - 10);
  doc.text(`Page ${pageNum}`, pageWidth - 14, pageHeight - 10, { align: "right" });
}

function getSeverityCounts(issues) {
  const c = { Critical: 0, High: 0, Medium: 0, Low: 0 };
  issues.forEach((i) => {
    if (c[i.severity] !== undefined) c[i.severity]++;
  });
  return c;
}

function getScoreGrade(score) {
  if (score >= 90) return { grade: "A+", color: [34, 197, 94], label: "Excellent Security Profile" };
  if (score >= 80) return { grade: "A", color: [34, 197, 94], label: "Highly Secure Profile" };
  if (score >= 70) return { grade: "B", color: [234, 179, 8], label: "Good Security Profile" };
  if (score >= 55) return { grade: "C", color: [249, 115, 22], label: "Fair Security Profile" };
  if (score >= 40) return { grade: "D", color: [239, 68, 68], label: "Poor Security Profile" };
  return { grade: "F", color: [239, 68, 68], label: "Critical Vulnerabilities Present" };
}

function getTopRecommendations(issues) {
  const severityOrder = { Critical: 4, High: 3, Medium: 2, Low: 1 };
  const sorted = [...issues].sort(
    (a, b) => (severityOrder[b.severity || "Low"] || 0) - (severityOrder[a.severity || "Low"] || 0)
  );
  const unique = [];
  const seen = new Set();
  for (const issue of sorted) {
    const key = (issue.suggestion || issue.description || "").substring(0, 80);
    if (!seen.has(key)) {
      seen.add(key);
      unique.push(issue);
    }
    if (unique.length >= 3) break;
  }
  return unique.map((i) => `[${i.severity}] ${i.suggestion || i.description}`);
}

/**
 * Generate the premium PDF report
 */
export function generateProfessionalPDF(scanResult, chartRef) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const issues = scanResult.issues || [];
  const severity = getSeverityCounts(issues);
  const score = scanResult.overall_score || 0;
  const { grade, color: gradeColor, label: gradeLabel } = getScoreGrade(score);
  let pageNum = 0;

  // ===================================
  // PAGE 1: EXECUTIVE COVER PAGE
  // ===================================
  pageNum++;
  
  // Clean white base background
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Left Accent Branding Bar
  doc.setFillColor(99, 102, 241); // Indigo 500
  doc.rect(0, 0, 8, pageHeight, "F");

  // Top-Right Geometric Decors
  doc.setFillColor(248, 250, 252); // Slate 50
  doc.triangle(pageWidth - 65, 0, pageWidth, 0, pageWidth, 65, "F");
  doc.setFillColor(238, 242, 255); // Indigo 50
  doc.triangle(pageWidth - 45, 0, pageWidth, 0, pageWidth, 45, "F");

  // Report Branding Headers
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42); // Slate 900
  doc.text("Security Audit Report", 25, 90);

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(99, 102, 241); // Indigo 500
  doc.text("AI Code Reviewer & Security Auditor", 25, 102);

  // Horizontal divider line
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.setLineWidth(0.5);
  doc.line(25, 112, pageWidth - 25, 112);

  // Score badge card container
  const cardX = 25;
  const cardY = 125;
  const cardW = 75;
  const cardH = 45;

  doc.setFillColor(248, 250, 252); // Slate 50 card background
  doc.setDrawColor(226, 232, 240); // Slate 200 border
  doc.roundedRect(cardX, cardY, cardW, cardH, 4, 4, "FD");

  // Modern concentric circle score ring inside the card
  const ringColor = score >= 80 ? [34, 197, 94] : score >= 60 ? [249, 115, 22] : [239, 68, 68];
  doc.setFillColor(...ringColor);
  doc.circle(cardX + 22, cardY + 22, 14, "F");
  doc.setFillColor(255, 255, 255);
  doc.circle(cardX + 22, cardY + 22, 11, "F");

  // Centered score text inside the ring
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42); // Slate 900
  doc.text(`${Math.round(score)}`, cardX + 22, cardY + 24, { align: "center" });

  // Grade labels inside card
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...ringColor);
  doc.text(grade, cardX + 48, cardY + 20);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text("Security Score", cardX + 48, cardY + 28);
  doc.text(gradeLabel.split(" ")[0], cardX + 48, cardY + 34);

  // Metadata block (aligned perfectly to the right side of the cover page)
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105); // Slate 600
  const metaX = 115;
  const metaY = 135;

  doc.setFont("helvetica", "bold");
  doc.text("AUDIT PROFILE", metaX, metaY - 8);
  doc.setFont("helvetica", "normal");

  doc.text(`Date:`, metaX, metaY);
  doc.setFont("helvetica", "bold");
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), metaX + 35, metaY);
  doc.setFont("helvetica", "normal");

  doc.text(`Files Scanned:`, metaX, metaY + 8);
  doc.text(`${scanResult.files_scanned || 0}`, metaX + 35, metaY + 8);

  doc.text(`Vulnerabilities:`, metaX, metaY + 16);
  doc.setTextColor(...(issues.length > 0 ? [239, 68, 68] : [34, 197, 94]));
  doc.setFont("helvetica", "bold");
  doc.text(`${issues.length} detected`, metaX + 35, metaY + 16);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);

  doc.text(`Scan Duration:`, metaX, metaY + 24);
  doc.text(`${scanResult.scan_duration || 0}s`, metaX + 35, metaY + 24);

  if (scanResult.scan_mode) {
    doc.text(`Scan profile:`, metaX, metaY + 32);
    doc.text(scanResult.scan_mode === "quick" ? "Quick Profile" : "Deep Profile", metaX + 35, metaY + 32);
  }

  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.setFont("helvetica", "bold");
  doc.text("Generated by AI Code Reviewer & Security Auditor", pageWidth / 2 + 10, pageHeight - 20, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.text("Confidential Report", pageWidth / 2 + 10, pageHeight - 13, { align: "center" });

  // ===================================
  // PAGE 2: EXECUTIVE SUMMARY & DASHBOARD
  // ===================================
  doc.addPage();
  pageNum++;
  addPageHeader(doc, pageWidth);
  addPageFooter(doc, pageWidth, pageHeight, pageNum);

  let y = 25;
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42); // Slate 900
  doc.text("Executive Summary", 14, y);
  y += 12;

  // Premium Score Metric Card
  doc.setFillColor(248, 250, 252); // Slate 50
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.roundedRect(14, y, 70, 24, 3, 3, "FD");

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text("Overall Security Score", 22, y + 8);
  
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...gradeColor);
  doc.text(`${Math.round(score)}`, 22, y + 18);
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text("/100", 45, y + 18);

  // Premium Grade Metric Card next to it
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(90, y, 106, 24, 3, 3, "FD");

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text("Security Rating & Evaluation", 98, y + 8);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...gradeColor);
  doc.text(`${gradeLabel} (Grade: ${grade})`, 98, y + 17);
  y += 32;

  // Scan metadata Info Box
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, y, pageWidth - 28, 24, 2, 2, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(`Scan Info: ${scanResult.scan_info || "N/A"}`, 18, y + 7);
  doc.text(
    `Duration: ${scanResult.scan_duration || 0} seconds  |  Files: ${scanResult.files_scanned || 0}  |  Vulnerabilities: ${issues.length} detected`,
    18, y + 16
  );
  y += 32;

  // Key Findings Table
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("Key Findings Assessment", 14, y);
  y += 5;

  autoTable(doc, {
    startY: y,
    head: [["Security Metric", "Scan Value", "Audit Assessment"]],
    body: [
      ["Overall Security Score", `${Math.round(score)}/100`, score >= 70 ? "Good" : score >= 40 ? "Warning" : "Critical"],
      ["Critical-Severity Vulnerabilities", `${severity.Critical}`, severity.Critical === 0 ? "None" : "Action Required"],
      ["High-Severity Vulnerabilities", `${severity.High}`, severity.High === 0 ? "None" : "Review Needed"],
      ["Medium-Severity Vulnerabilities", `${severity.Medium}`, severity.Medium <= 2 ? "Acceptable" : "Review"],
      ["Low-Severity Vulnerabilities", `${severity.Low}`, "Informational"],
      ["Average Cyclomatic Complexity", `${scanResult.metrics?.code_complexity || "N/A"}`, "-"],
      ["Source Code Duplication Rate", `${scanResult.metrics?.duplication_percentage || 0}%`, (scanResult.metrics?.duplication_percentage || 0) > 20 ? "High" : "OK"],
      ["Vulnerable Dependencies Count", `${scanResult.metrics?.vulnerable_dependencies || 0}`, (scanResult.metrics?.vulnerable_dependencies || 0) === 0 ? "None" : "Review"],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 3.5, font: "helvetica" },
    columnStyles: { 
      0: { fontStyle: "bold", cellWidth: 75 }, 
      1: { halign: "center", cellWidth: 35 }, 
      2: { cellWidth: "auto", fontStyle: "bold" } 
    },
    didDrawCell: (data) => {
      if (data.section === "body" && data.column.index === 2) {
        const textVal = data.cell.text[0];
        if (textVal === "Critical" || textVal === "Action Required") {
          doc.setTextColor(239, 68, 68); // Soft Crimson
        } else if (textVal === "Warning" || textVal === "Review Needed" || textVal === "Review" || textVal === "High") {
          doc.setTextColor(249, 115, 22); // Amber Orange
        } else if (textVal === "Good" || textVal === "None" || textVal === "Acceptable" || textVal === "OK") {
          doc.setTextColor(34, 197, 94); // Soft green
        }
      }
    }
  });
  y = doc.lastAutoTable.finalY + 10;

  // Top 3 Recommendations
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("Top Remediation Recommendations", 14, y);
  y += 8;

  const recs = getTopRecommendations(issues);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  recs.forEach((rec, i) => {
    const wrappedLines = doc.splitTextToSize(`${i + 1}. ${rec}`, pageWidth - 32);
    wrappedLines.forEach((line) => {
      if (y > pageHeight - 25) {
        doc.addPage();
        pageNum++;
        addPageHeader(doc, pageWidth);
        addPageFooter(doc, pageWidth, pageHeight, pageNum);
        y = 25;
      }
      doc.text(line, 18, y);
      y += 4.5;
    });
    y += 1.5;
  });

  // ===================================
  // PAGE 3: RISK MATRIX & CHARTS
  // ===================================
  doc.addPage();
  pageNum++;
  addPageHeader(doc, pageWidth);
  addPageFooter(doc, pageWidth, pageHeight, pageNum);

  y = 25;
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("Risk Distribution Profile", 14, y);
  y += 15;

  const matrixX = 25;
  const cellW = 35;
  const cellH = 18;
  const riskLevels = ["Critical", "High", "Medium", "Low"];
  const riskColors = { 
    Critical: [239, 68, 68], 
    High: [249, 115, 22], 
    Medium: [234, 179, 8], 
    Low: [6, 182, 212] 
  };

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text("Severity", matrixX, y + 4);
  doc.text("Issues Count", matrixX + 50, y + 4);
  doc.text("Severity Share Percentage Indicator", matrixX + 90, y + 4);
  
  doc.setDrawColor(241, 245, 249);
  doc.line(14, y + 8, pageWidth - 14, y + 8);
  y += 14;

  const totalIssues = issues.length || 1;

  riskLevels.forEach((level) => {
    const count = severity[level] || 0;
    const sharePct = Math.round((count / totalIssues) * 100);

    // Rounded badge for Level Name
    doc.setFillColor(...riskColors[level]);
    doc.roundedRect(matrixX, y - 5, 32, 12, 2, 2, "F");
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(level, matrixX + 16, y + 3, { align: "center" });

    // Issues count text
    doc.setTextColor(15, 23, 42); // Slate 900
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`${count}`, matrixX + 62.5, y + 4, { align: "center" });

    // Premium progress bar
    const barMaxWidth = 70;
    const barWidth = (count / totalIssues) * barMaxWidth;
    
    doc.setFillColor(241, 245, 249); // Slate 100 background
    doc.roundedRect(matrixX + 90, y - 2, barMaxWidth, 8, 2, 2, "F");
    
    if (barWidth > 0) {
      doc.setFillColor(...riskColors[level]);
      doc.roundedRect(matrixX + 90, y - 2, barWidth, 8, 2, 2, "F");
    }
    
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 116, 139);
    doc.text(`${sharePct}%`, matrixX + 90 + barMaxWidth + 5, y + 4);

    y += cellH;
  });
  y += 10;

  // Chart Rendering
  const chart = chartRef?.current;
  if (chart && typeof chart.toBase64Image === "function") {
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text("Visual Vulnerability Breakdown", 14, y);
    y += 8;
    try {
      const chartImage = chart.toBase64Image("image/png", 1.0);
      doc.addImage(chartImage, "PNG", pageWidth / 2 - 40, y, 80, 80);
    } catch {
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text("Chart rendering unavailable.", 30, y + 10);
    }
    y += 90;
  }

  // Issues by file type summary
  if (issues.length > 0) {
    const fileTypeMap = {};
    issues.forEach((issue) => {
      const file = issue.file || "";
      const ext = file.includes(".") ? `.${file.split(".").pop().toLowerCase()}` : "other";
      fileTypeMap[ext] = (fileTypeMap[ext] || 0) + 1;
    });
    const fileTypes = Object.entries(fileTypeMap).sort((a, b) => b[1] - a[1]).slice(0, 8);

    if (y > pageHeight - 60) {
      doc.addPage();
      pageNum++;
      addPageHeader(doc, pageWidth);
      addPageFooter(doc, pageWidth, pageHeight, pageNum);
      y = 25;
    }

    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text("Vulnerabilities by Extension", 14, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [["File Extension", "Issues Count", "Share Percentage"]],
      body: fileTypes.map(([ext, count]) => [ext, count, `${Math.round((count / issues.length) * 100)}%`]),
      theme: "grid",
      headStyles: { fillColor: [124, 58, 237], textColor: [255, 255, 255] },
      styles: { fontSize: 8, font: "helvetica", cellPadding: 2 },
    });
    y = doc.lastAutoTable.finalY + 10;
  }

  // ===================================
  // PAGE 4+: DETAILED AUDIT FINDINGS
  // ===================================
  doc.addPage();
  pageNum++;
  addPageHeader(doc, pageWidth);
  addPageFooter(doc, pageWidth, pageHeight, pageNum);

  y = 25;
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("Detailed Security Findings", 14, y);
  y += 12;

  if (issues.length === 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(34, 197, 94);
    doc.text("No security vulnerabilities were detected. Great job!", 14, y);
  } else {
    const issuesBody = issues.map((i, idx) => [
      idx + 1,
      i.severity || "Low",
      i.file || "N/A",
      i.description || "",
      i.suggestion || "",
    ]);

    autoTable(doc, {
      startY: y,
      head: [["#", "Severity", "Target File", "Finding Description", "Remediation Strategy"]],
      body: issuesBody,
      theme: "striped",
      headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255], fontStyle: "bold" },
      styles: { fontSize: 7, cellPadding: 3, valign: "top", overflow: "linebreak", font: "helvetica" },
      columnStyles: {
        0: { cellWidth: 8, halign: "center" },
        1: { cellWidth: 18, fontStyle: "bold" },
        2: { cellWidth: 32 },
        3: { cellWidth: "auto" },
        4: { cellWidth: "auto" },
      },
      didDrawCell: (data) => {
        if (data.section === "body" && data.column.index === 1) {
          const sev = data.cell.raw;
          const col = SEVERITY_COLORS[sev] || [100, 100, 100];
          doc.setFillColor(...col);
          doc.roundedRect(data.cell.x + 1, data.cell.y + 1, data.cell.width - 2, data.cell.height - 2, 1, 1, "F");
          doc.setTextColor(255, 255, 255);
          doc.setFontSize(6.5);
          doc.setFont("helvetica", "bold");
          doc.text(String(sev), data.cell.x + data.cell.width / 2, data.cell.y + data.cell.height / 2 + 1, { align: "center" });
        }
      },
      didDrawPage: () => {
        pageNum++;
        addPageHeader(doc, pageWidth);
        addPageFooter(doc, pageWidth, pageHeight, pageNum);
      },
    });
    y = doc.lastAutoTable.finalY + 10;
  }

  // ===================================
  // REMEDIATION TICKETS & PRIORITY
  // ===================================
  if (issues.length > 0) {
    if (y > pageHeight - 60) {
      doc.addPage();
      pageNum++;
      addPageHeader(doc, pageWidth);
      addPageFooter(doc, pageWidth, pageHeight, pageNum);
      y = 25;
    }

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text("Remediation Priority Tickets", 14, y);
    y += 10;

    const severityOrder = { Critical: 4, High: 3, Medium: 2, Low: 1 };
    const sortedIssues = [...issues].sort(
      (a, b) => (severityOrder[b.severity || "Low"] || 0) - (severityOrder[a.severity || "Low"] || 0)
    );

    const getEffort = (sev) => {
      switch (sev) {
        case "Critical": return "High (> 4 hours)";
        case "High": return "Medium (1-4 hours)";
        case "Medium": return "Low (< 1 hour)";
        case "Low": return "Minimal (< 30 min)";
        default: return "TBD";
      }
    };
    const getPriority = (sev) => {
      switch (sev) {
        case "Critical": return "Fix Immediately";
        case "High": return "Fix This Week";
        case "Medium": return "Fix This Sprint";
        case "Low": return "Schedule Later";
        default: return "Schedule";
      }
    };

    const remBody = sortedIssues.slice(0, 20).map((i, idx) => [
      idx + 1,
      i.severity || "Low",
      i.file || "N/A",
      (i.description || "").substring(0, 60) + ((i.description || "").length > 60 ? "..." : ""),
      getEffort(i.severity),
      getPriority(i.severity),
    ]);

    autoTable(doc, {
      startY: y,
      head: [["#", "Severity", "Target File", "Issue Summary", "Effort Estimate", "Remediation Ticket"]],
      body: remBody,
      theme: "grid",
      headStyles: { fillColor: [124, 58, 237], textColor: [255, 255, 255], fontStyle: "bold" },
      styles: { fontSize: 7, cellPadding: 3, font: "helvetica" },
      columnStyles: {
        0: { cellWidth: 8, halign: "center" },
        1: { cellWidth: 16, fontStyle: "bold" },
        2: { cellWidth: 30 },
        3: { cellWidth: "auto" },
        4: { cellWidth: 28 },
        5: { cellWidth: 28 },
      },
      didDrawCell: (data) => {
        if (data.section === "body" && data.column.index === 1) {
          const sev = data.cell.raw;
          const col = SEVERITY_COLORS[sev] || [100, 100, 100];
          doc.setFillColor(...col);
          doc.roundedRect(data.cell.x + 1, data.cell.y + 1, data.cell.width - 2, data.cell.height - 2, 1, 1, "F");
          doc.setTextColor(255, 255, 255);
          doc.setFontSize(6.5);
          doc.setFont("helvetica", "bold");
          doc.text(String(sev), data.cell.x + data.cell.width / 2, data.cell.y + data.cell.height / 2 + 1, { align: "center" });
        }
      },
      didDrawPage: () => {
        pageNum++;
        addPageHeader(doc, pageWidth);
        addPageFooter(doc, pageWidth, pageHeight, pageNum);
      },
    });
    y = doc.lastAutoTable.finalY + 10;
  }

  // ===================================
  // APPENDIX: AUDIT METHODOLOGY
  // ===================================
  doc.addPage();
  pageNum++;
  addPageHeader(doc, pageWidth);
  addPageFooter(doc, pageWidth, pageHeight, pageNum);

  y = 25;
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("Appendix: Audit Methodology", 14, y);
  y += 12;

  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);

  const methodology = [
    "Scanning Methodology:",
    "",
    "1. Code Ingestion: Source code is uploaded via ZIP file, GitHub URL, or direct paste.",
    "2. File Discovery: All supported source files are identified and enumerated.",
    "3. Static Analysis: Each file is analyzed for cyclomatic complexity and code duplication rates.",
    "4. AI Security Audit: Google Gemini AI performs deep static analysis to uncover critical vulnerabilities.",
    "5. Caching: Results are cached using SHA-256 content hashing for sub-second performance.",
    "6. Scoring: Overall security score is computed dynamically based on these metrics:",
    "   - Code complexity penalty (max 30 points)",
    "   - Code duplication penalty (max 25 points)",
    "   - Issues found penalty (max 35 points)",
    "   - Vulnerable dependencies penalty (max 10 points)",
    "",
    "Scan Profiles:",
    "- Quick Profile: Focused on OWASP Top 10 vulnerabilities for rapid verification.",
    "- Deep Profile: Comprehensive security analysis covering 50+ vulnerability vectors.",
    "",
    "Severity Classifications:",
    "- Critical (9-10): Immediate exploitation risk, severe direct threats.",
    "- High (7-8): Significant security weakness, remediate within this week.",
    "- Medium (4-6): Moderate vulnerability, schedule within the current sprint.",
    "- Low (1-3): Best practice or security posture enhancement.",
    "",
    "Supported Languages: Python, JavaScript, TypeScript, Java, C, C++, C#, Go, Rust,",
    "PHP, Ruby, Swift, Kotlin, Scala, HTML, CSS, SQL, Shell, YAML, XML, Dart, R, Perl.",
    "",
    `Report generated on: ${new Date().toLocaleString()}`,
    `Scan duration: ${scanResult.scan_duration || 0} seconds`,
    `Files analyzed: ${scanResult.files_scanned || 0}`,
  ];

  methodology.forEach((line) => {
    if (y > pageHeight - 20) {
      doc.addPage();
      pageNum++;
      addPageHeader(doc, pageWidth);
      addPageFooter(doc, pageWidth, pageHeight, pageNum);
      y = 25;
    }
    if (
      line.startsWith("Scanning Methodology:") ||
      line.startsWith("Scan Profiles:") ||
      line.startsWith("Severity Classifications:") ||
      line.startsWith("Supported Languages:")
    ) {
      doc.setFont("helvetica", "bold");
      doc.setTextColor(15, 23, 42);
    } else {
      doc.setFont("helvetica", "normal");
      doc.setTextColor(71, 85, 105);
    }
    doc.text(line, 18, y);
    y += 5.5;
  });

  // Export File
  const timestamp = new Date().toISOString().slice(0, 10);
  doc.save(`Security_Audit_Report_${timestamp}.pdf`);
}
